### PR TITLE
Add TH2I & TH1I

### PR DESCRIPTION
**Pull request by pmandrik**
Following comment:
https://github.com/cms-sw/cmssw/pull/37665#issuecomment-1112359823

add TH2I to the same places where TH2S is.

### CODE REVIEW

**Comment by mmusich** [comment]
@pmandrik @emanueleusai what's the plan to merge this for production.
It's needed for https://github.com/cms-sw/cmssw/pull/37860 and https://github.com/cms-sw/cmssw/pull/37836.

@sroychow FYI

**Comment by emanueleusai** [comment]
We will follow up on this asap

**Comment by pmandrik** [comment]
For my memory, at the moment trying  to compile old GUI at lxplus as following (https://github.com/cms-sw/cmssw/issues/33053#issuecomment-795791550) :
```
ssh cmsdev20.cern.ch
git clone git@github.com:cms-sw/cmsdist -b comp_gcc630
git clone git@github.com:cms-sw/pkgtools -b V00-33-XX
# update cmsdist/dqmgui.spec to use tag from dev128 branch where this PR is included
./pkgtools/cmsBuild --repo comp -a slc7_amd64_gcc630 -i w -j 10 build dqmgui
```

**Comment by pmandrik** [comment]
Hi, @mmusich ,
we have a following problem to compile the old gui with this PR due to error:
./DQM/serverext.cc:947:73: error: 'DQM_PROP_TYPE_TH2I' is not a member of 'DQMNet'
                                                               : type == DQMNet::DQM_PROP_TYPE_TH2I ? "TH2I"
                                                               
because the environment to build old gui is defined in:
https://github.com/cms-sw/cmsdist/blob/comp_gcc630/dqmgui.spec
from my understanding looks like normally we need an DQMNet update with TH2I backported to CMSSW_7_6_X.

I think, @smuzaffar could clarify.

**Comment by mmusich** [comment]
Hi @pmandrik, 

> from my understanding looks like normally we need an DQMNet update with TH2I backported to CMSSW_7_6_X.

Why 7.6.x in particular?

**Comment by mmusich** [comment]
Can't this line

https://github.com/cms-sw/cmsdist/blob/5555bbbb544e4c99aa5587e53d13586991ad399d/dqmgui.spec#L15

Be updated to use something more modern?

**Comment by smuzaffar** [comment]
> ./pkgtools/cmsBuild --repo comp -a slc7_amd64_gcc630 -i w -j 10 build dqmgui

yes you can, but moving to latest DQMServices might bring in other issues e.g. it might not compile with gcc 6.3 any more. I would suggest that if you still want to support the old dqmgui then get `http://cmsrep.cern.ch/cgi-bin/cmspkg/SOURCES/comp/541fd3225b47e8d956e39722284df159/DQMCore.tar.gz` which is a cached version of https://github.com/cms-sw/cmsdist/blob/5555bbbb544e4c99aa5587e53d13586991ad399d/dqmgui.spec#L15  and add a new github repository e.g `cms-DQM/cmssw-dqm` using then contents of `DQMCore.tar.gz` and add the extra code to support `TH2I and TH1I` in  `cms-DQM/cmssw-dqm` and update the https://github.com/cms-sw/cmsdist/blob/5555bbbb544e4c99aa5587e53d13586991ad399d/dqmgui.spec#L15 to use new  `cms-DQM/cmssw-dqm` instead of checking of code from cmssw.

**Comment by pmandrik** [comment]
Hi, @smuzaffar,  thank you, I will follow your advice adding DQMCore code to the GUI repo.
